apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: HelmRelease
    patch: |
      - op: add
        path: /spec/values
        value:
          podSecurityStandard: baseline
          podSecuritySeverity: medium
          validationFailureAction: Audit
          background: true
          policyExclude:
            all:
              any:
                - resources:
                    namespaces:
                      - cert-manager
                      - external-secrets
                      - flux-system
                      - grafana
                      - kube-node-lease
                      - kube-public
                      - kube-system
                      - kyverno
                      - linkerd
                      - monitoring
                      - platform-system
                      - traefik
