apiVersion: v1
kind: Secret
metadata:
  name: headscale-config
  namespace: headscale
stringData:
  config.yaml: |
    server_url: "https://hs.altinn.cloud"
    listen_addr: "0.0.0.0:8080"
    metrics_listen_addr: "0.0.0.0:9090"
    grpc_listen_addr: "0.0.0.0:50443"
    grpc_allow_insecure: false
    tls_cert_path: ""
    tls_key_path: ""
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    disable_check_updates: true
    ephemeral_node_inactivity_timeout: 30m
    randomize_client_port: false
    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite
        write_ahead_log: true
        wal_autocheckpoint: 1000
    prefixes:
      v6: fd7a:115c:a1e0:0070::/64
      v4: 100.70.0.0/16
      allocation: sequential
    derp:
      server:
        enabled: true
        region_id: 999
        region_code: "headscale-server"
        region_name: "HeadScale"
        stun_listen_addr: "0.0.0.0:3478"
        automatically_add_embedded_derp_region: true
        verify_clients: true
        ipv4: "${PUBLIC_IP_V4}"
        ipv6: "${PUBLIC_IP_V6}"
        private_key_path: /var/lib/headscale/derp_server_private.key
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 3h
    dns:
      override_local_dns: true
      nameservers:
        global:
          - 1.1.1.2
          - 2606:4700:4700::1112
      search_domains:
        - altinn.cloud
      magic_dns: true
      base_domain: ts.altinn.cloud
    policy:
      mode: "database"
    oidc:
      issuer: "https://login.microsoftonline.com/cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c/v2.0"
      client_id: "${HEADSCALE_APP_CLIENT_ID}"
      client_secret: "${HEADSCALE_APP_CLIENT_SECRET}"
      expiry: 0
      scope: ["openid", "profile", "email"]
      allowed_groups:
        - "${HEADSCALE_APP_ALLOWED_GROUP}"
      extra_params:
        domain_hint: altinn.cloud
        prompt: select_account
    log:
      format: text
      level: info
    logtail:
      enabled: false
    taildrop:
      enabled: true
    unix_socket: /var/run/headscale/headscale.sock
    unix_socket_permission: "0770"
