apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: OCIRepository
      name: dis-apim-operator
    patch: |
      - op: replace
        path: /metadata/namespace
        value: platform-system
  - target:
      kind: Kustomization
      name: dis-apim-operator
    patch: |
      - op: replace
        path: /metadata/namespace
        value: platform-system
      - op: replace
        path: /spec/sourceRef/namespace
        value: platform-system
