apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ttd.apps.yt01.altinn.cloud.yaml
  - ttd.apps.yt01.altinn.cloud-push.yaml
  - ttd.apps.at24.altinn.cloud.yaml
  - ttd.apps.at24.altinn.cloud-push.yaml
  - ttd.apps.at23.altinn.cloud.yaml
  - ttd.apps.at23.altinn.cloud-push.yaml
  - ttd.apps.at22.altinn.cloud.yaml
  - ttd.apps.at22.altinn.cloud-push.yaml
  - af.yt01.altinn.cloud.yaml
  - af.yt01.altinn.cloud-push.yaml
  - af.at23.altinn.cloud.yaml
  - af.at23.altinn.cloud-push.yaml
  - af.tt02.altinn.no.yaml
  - af.tt02.altinn.no-push.yaml
