apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - ../base
patches:
  - target:
      kind: HelmRelease
      name: linkerd-crds
    patch: |
      - op: replace
        path: /metadata/namespace
        value: platform-system
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: platform-system
  - target:
      kind: HelmRelease
      name: linkerd
    patch: |
      - op: replace
        path: /spec/dependsOn/0/namespace
        value: platform-system
      - op: replace
        path: /spec/dependsOn/1/namespace
        value: platform-system
